In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("IRIS.csv")
df2=df.copy()

In [3]:
# first 10 rows
df2.head(10)
# shape of dataset
df2.shape
# datatypes
df2.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [14]:
# only those rows where petal length > 4.5
df2=df2[df2["petal_length"]>4.5]
# only those rows where species is "Iris-virginica"
df2=df2[df2["species"]=="Iris-virginica"]
# both conditions
df2=df2[(df2["petal_length"]>4.5) & (df2["species"]=="Iris-virginica")]

In [20]:
# Group by species and compute the "average sepal_length", "maximum petal_width", and "standard deviation of sepal_width"
df2=df.copy()
df2.groupby("species").agg(
    avg_sepal_len=("sepal_length","mean"),
    max_petal_width=("petal_width","max"),
    std_sepal_width=("sepal_width","std")
)

                 avg_sepal_len  max_petal_width  std_sepal_width
species
Iris-setosa              5.006              0.6         0.381024
Iris-versicolor          5.936              1.8         0.313798
Iris-virginica           6.588              2.5         0.322497

In [27]:
# Create a new column "petal_ratio" = petal_length / petal_width. For each species, find the average petal_ratio.
df2["petal_ratio"]=df2["petal_length"]/df2["petal_width"]
df2.groupby("species")["petal_ratio"].mean()

species
Iris-setosa        7.078000
Iris-versicolor    3.242837
Iris-virginica     2.780662
Name: petal_ratio, dtype: float64

In [24]:
df2

,sepal_length,sepal_width,petal_length,petal_width,species,petal_ratio
0,5.1,3.5,1.4,0.2,Iris-setosa,7.000000
1,4.9,3.0,1.4,0.2,Iris-setosa,7.000000
2,4.7,3.2,1.3,0.2,Iris-setosa,6.500000
3,4.6,3.1,1.5,0.2,Iris-setosa,7.500000
4,5.0,3.6,1.4,0.2,Iris-setosa,7.000000
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,2.260870
146,6.3,2.5,5.0,1.9,Iris-virginica,2.631579
147,6.5,3.0,5.2,2.0,Iris-virginica,2.600000
148,6.2,3.4,5.4,2.3,Iris-virginica,2.347826
149,5.9,3.0,5.1,1.8,Iris-virginica,2.833333